version: "3.3"
services:
  prod:
    build: ./prod-api/
    ports:
      - "5000:5000"
      - "9091:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: production
  trainer:
    build: ./trainer-api/
    ports:
      - "5001:5000"
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: trainer
  data:
    build: ./data-api/
    ports:
      - "5002:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: data
  staticprod:
    build: ./staticprod-api/
    ports:
      - "5003:5000"
      - "9092:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: static-production